project:
  type: website
  output-dir: _site
  preview:
    browser: true
  render:
    - "index.qmd"
    - "about.qmd"
    - "keywords.qmd"
    - "strategies.qmd"
  resources: 
    - shinylive-sw.js
    - keywords.csv
    - "description.Rmd"

website:  
  repo-url: https://github.com/jhelvy/magaScreener
  repo-actions: [edit, issue]
  title: "MAGA Keyword Screener"
  navbar:
    search: false
    left:
      - text: "Screener"
        file: index.qmd
      - text: "About"
        file: about.qmd
      - text: "Keywords"
        file: keywords.qmd
      - text: "Strategies"
        file: strategies.qmd
    right: 
      - icon: github
        href: https://github.com/jhelvy/magaScreener
  page-footer:
    center:
      - text: "Site made with <a href='https://github.com/jhelvy/jhelvy_quarto' target='_blank'><i class='bi bi-git'></i></a>, <a href='https://quarto.org/' target='_blank'><img src='https://quarto.org/favicon.png' width=12> quarto</a>, and rage"
format:
  html:
    theme: [default, theme.scss]
    page-layout: full
    toc: true
